#! /bin/sh
# Autostart
. "${HOME}/.cache/wal/colors.sh" &
wal -i ~/Pictures/Wallpapers/ &
bash ~/.config/polybar/launch &
xsetroot -cursor_name left_ptr &
dunst &
xautolock -time 10 -corners ---- -locker slock &

bspc config focus_follows_pointer true
bspc config split_ratio 0.58

# Workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 0


# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color1"
#bspc config focused_border_color "$color1"

# Border
bspc config border_width 0

# Gap
bspc config window_gap 8

# Monocle
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

# Float
bspc rule -a Lxappearance         state=floating
bspc rule -a mpv                  state=floating
bspc rule -a Emacs                 state=tiled
bspc rule -a Zathura              state=tiled
